#!/bin/bash

#Gather System Information
source /etc/os-release
UPTIME=$(uptime -p)
HOSTNAME=$hostname

#Gather CPU Information
CPU_MODEL=$(lscpu | grep -i 'model name' | cut -d: -f2 | xargs)

CURRENT_SPEED=$(sudo lshw -c cpu | grep size | awk -F: 'NR == 1 {print $2}')
MAX_SPEED=$(sudo lshw -c cpu | grep capacity | awk -F: 'NR == 1 {print $2}')

#RAM Info
RAM_SIZE=$(free -h | awk 'NR==2 {print $2}')

#Disk Information
DISK_MODEL=$(sudo lshw -c disk | grep -A6 '*-disk' | grep product | awk 'NR==1 {print $2')

#GPU Information



cat <<EOF
System Report generated by $USER, $(date)

System Information
-------------------------
Hostname: $HOSTNAME
OS: $PRETTY_NAME
Uptime: $UPTIME

Hardware Information
-------------------------
cpu: $CPU_MODEL
Speed: $CURRENT_SPEED , Maximum $MAX_SPEED
RAM: $RAM_SIZE
Disk(s): $DISK_MODEL
Video: $GPU_INFO
EOF
