#!/bin/bash

#Gather System Information
source /etc/os-release
UPTIME=$(uptime -p)
HOSTNAME=$(hostname)

#Gather CPU Information
CPU_MODEL=$(lscpu | grep -i 'model name' | cut -d: -f2 | xargs)
CURRENT_SPEED=$(sudo lshw -c cpu | grep size | awk -F: 'NR == 1 {print $2}')
MAX_SPEED=$(sudo lshw -c cpu | grep capacity | awk -F: 'NR == 1 {print $2}')

#RAM Info
RAM_SIZE=$(free -h | awk 'NR==2 {print $2}')

#Disk Information
DISK_MODEL=$(sudo lshw -c disk | grep -A6 '*-disk' | grep product | cut -d: -f2 | xargs)

#GPU Information
GPU_INFO=$(echo "temp")

#Network Information
FQDN=$(hostname --fqdn)
HOSTNAME_IP=$(nslookup $FQDN | grep $FQDN -A1 | awk 'NR==2 {print $2}')
GATEWAY_ADDRESS=$(ip r | awk 'NR==1 {print $3}')
DNS_SERVER=$(cat /run/systemd/resolve/resolv.conf | grep nameserver | cut -d ' ' -f2)

NIC_MODEL=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==1' | cut -d: -f2 | xargs)

NIC_VENDOR=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==2' | cut -d: -f2 | xargs)

INTERFACE_NAME=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==3' | cut -d: -f2 | xargs)

IP_ADDRESS=$(ip -4 -o address show scope global | awk 'NR==1 {print $4}')

cat <<EOF
System Report generated by $USER, $(date)

System Information
-------------------------
Hostname: $HOSTNAME
OS: $PRETTY_NAME
Uptime: $UPTIME

Hardware Information
-------------------------
cpu: $CPU_MODEL
Speed: $CURRENT_SPEED , Maximum $MAX_SPEED
RAM: $RAM_SIZE
Disk(s): $DISK_MODEL
Video: $GPU_INFO

Network Information
-------------------------
FQDN: $FQDN
Host Address: $HOSTNAME_IP
Gateway IP: $GATEWAY_ADDRESS
DNS Server: $DNS_SERVER

$INTERFACE_NAME: $NIC_VENDOR $NIC_MODEL
IP Address: $IP_ADDRESS
EOF
