#!/bin/bash


#Get Date
DATE=$(date)
#Gather System Information
source /etc/os-release
UPTIME=$(uptime -p)
HOSTNAME=$(hostname)

#Gather CPU Information
CPU_MODEL=$(lscpu | grep -i 'model name' | cut -d: -f2 | xargs)
CURRENT_SPEED=$(sudo lshw -c cpu | grep size | awk -F: 'NR == 1 {print $2}')
MAX_SPEED=$(sudo lshw -c cpu | grep capacity | awk -F: 'NR == 1 {print $2}')

#RAM Info
RAM_SIZE=$(free -h | awk 'NR==2 {print $2}')

#Disk Information
DISK_MODEL=$(sudo lshw -c disk | grep -A6 '*-disk' | grep product | cut -d: -f2 | xargs)

#GPU Information
GPU_MODEL=$(sudo lshw -C display | grep product | cut -d: -f2 | xargs)
GPU_MAKE=$(sudo lshw -C display | grep vendor | cut -d: -f2 | xargs)

#Network Information
FQDN=$(hostname --fqdn)
HOSTNAME_IP=$(nslookup $FQDN | grep $FQDN -A1 | awk 'NR==2 {print $2}')
GATEWAY_ADDRESS=$(ip r | awk 'NR==1 {print $3}')
DNS_SERVER=$(cat /run/systemd/resolve/resolv.conf | grep nameserver | cut -d ' ' -f2)

NIC_MODEL=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==1' | cut -d: -f2 | xargs)

NIC_VENDOR=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==2' | cut -d: -f2 | xargs)

INTERFACE_NAME=$(sudo lshw -c network | grep 'product\|vendor\|logical name' | awk 'NR==3' | cut -d: -f2 | xargs)

IP_ADDRESS=$(ip -4 -o address show scope global | awk 'NR==1 {print $4}')


## Gather system status information
LOGGED_IN=$(who -q | awk 'NR==1' | tr ' ' ',')
DISK_SPACE=$(echo 'Temp')
PROCESS_COUNT=$(ps -auxh | wc -l)
LOAD_AVERAGES=$(uptime | awk -F 'load average: ' '{print $2}')

TOTAL_RAM=$(free -h | awk 'NR==2 {print $2}')
USED_RAM=$(free -h | awk 'NR==2 {print $3}')
AVAILABLE_RAM=$(free -h | awk 'NR==2 {print $4}')

LISTENING_PORTS=$(ss -tuln -4 | grep LISTEN | cut -d: -f2 | cut -d ' ' -f1 |  tr '\n' ', ')
UFW_INFO=$(echo 'Temp')


cat <<EOF

System Report generated by $USER at $DATE

System Information
-------------------------
Hostname: $HOSTNAME
OS: $PRETTY_NAME
Uptime: $UPTIME

Hardware Information
-------------------------
cpu: $CPU_MODEL
Speed: Current $CURRENT_SPEED, Maximum $MAX_SPEED
RAM: $RAM_SIZE
Disk: $DISK_MODEL
Video: $GPU_MAKE $GPU_MODEL

Network Information
-------------------------
FQDN: $FQDN
Host Address: $HOSTNAME_IP
Gateway IP: $GATEWAY_ADDRESS
DNS Server: $DNS_SERVER

$INTERFACE_NAME: $NIC_VENDOR $NIC_MODEL
IP Address: $IP_ADDRESS

System Status
-------------------------
Users Logged In: $LOGGED_IN
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: Total RAM = $TOTAL_RAM, Used RAM = $USED_RAM, Free RAM = $AVAILABLE_RAM
Listening Network Ports: $LISTENING_PORTS
UFW Rules: DATA FROM UFW SHOW
EOF

